# github cicd
name: deploy-manifests
on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: "${{ secrets.SERVER_SSH }}"
          port: 22
          script: |
            sudo microk8s kubectl apply -f infra/k8s --insecure-skip-tls-verify && sudo microk8s kubectl apply -f infra/k8s-prod --insecure-skip-tls-verify
      # - name: Login to Server and get context
      #   run: doctl kubernetes cluster kubeconfig save ticketing
      # - name: Apply updated manifest
      #   run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
