import type { NextPage } from 'next';
import Head from 'next/head';

// import layout
import DesignerTemplate from '@/components/template/Designer/Designer';

const DesignerPage: NextPage = () => {
    return (
        <>
            <Head>
            <title>لمک - طراحی</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <DesignerTemplate />
        </>
    )
}

export default DesignerPage

