import type { NextPage } from 'next';
import Head from 'next/head';

// import layout
import DashboardTemplate from '@/components/template/Dashboard/Dashboard';

// import interface
import { iAction } from '@/interfaces/Interfaces';

const actionArray: iAction[] = [
    {
        name: 'طراحی',
        link: '/dashboard/designer',
        image: "/images/actions/design.png"
    },
    {
        name: 'ساخت',
        link: '/dashboard/designs',
        image: "/images/actions/create.png"
    }
]

const DashboardPage: NextPage = () => {
    return (
        <>
            <Head>
            <title>لمک - داشبورد</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <DashboardTemplate items={actionArray}/>
        </>
    )
}

export default DashboardPage

